version: "3.9"

services:
  pipeline:
    build: .
    container_name: ecommerce_pipeline
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chaituram@1918
